import type { Metadata } from "next";
import { Abhaya_Libre, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";

const abhayaLibre = Montserrat({
  variable: "--font-abhaya",
  weight: ["400", "500", "600", "700", "800"],
  display: "swap",
  // subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${abhayaLibre.className} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
