# Generated by Django 5.2.3 on 2025-06-26 04:32

import django.core.validators
import main.models
import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('price', models.IntegerField(default=0)),
                ('image', models.FileField(upload_to=main.models.get_path_upload_post_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg']), main.validators.FileSizeValidator(megabyte_limit=32)])),
                ('street', models.CharField()),
                ('houseNumber', models.CharField(choices=[('draft', 'Studio'), ('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four')], default='1')),
            ],
        ),
    ]
