# Generated by Django 5.2.3 on 2025-06-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
