# Generated by Django 5.2.3 on 2025-06-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_housenumber_layout_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='houseNumber',
            field=models.CharField(default=''),
        ),
    ]
