# Generated by Django 5.2.3 on 2025-06-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_layout_housenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='rooms',
            field=models.CharField(choices=[('Студия', 'Studio'), ('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four')], default='1'),
        ),
    ]
